// xTHIS FILE IS node.js WORKING

export const users = [
  {
    id: '4',
    name: 'Beautiful T-Shirt',
    favoriteColor: 'From favorite Color to Description',
    price: { amount: '250', currency: 'euro' },
    colorChoice: { black: 'black', brown: 'brown', red: 'red' },
    img: 'https://i.imgur.com/G3ZWEv4.jpg',
  },
  {
    id: '5',
    name: 'Another Wonderful T-Shirt',
    favoriteColor: 'From favorite Color to Description',
    price: { amount: '410', currency: 'euro' },
    colorChoice: { black: 'black', brown: 'brown', red: 'red' },
    img: 'https://i.imgur.com/G3ZWEv4.jpg',
  },
  {
    id: '6',
    name: 'Women Leather Bags',
    favoriteColor: 'From favorite Color to Description',
    price: { amount: '150', currency: 'euro' },
    colorChoice: { black: 'black', brown: 'brown', red: 'red' },
    img: 'https://i.imgur.com/G3ZWEv4.jpg',
  },
  {
    id: '7',
    name: 'Another Wonderful Male Bag',
    favoriteColor: 'From favorite Color to Description',
    price: { amount: '50', currency: 'euro' },
    colorChoice: { black: 'black', brown: 'brown', red: 'red' },
    img: 'https://i.imgur.com/G3ZWEv4.jpg',
  },
  {
    id: '8',
    name: 'Another Wonderful Male Bag',
    favoriteColor: 'From favorite Color to Description',
    price: { amount: '60', currency: 'euro' },
    colorChoice: { black: 'black', brown: 'brown', red: 'red' },
    img: 'https://i.imgur.com/G3ZWEv4.jpg',
  },
  {
    id: '9',
    name: 'Another Wonderful Male Bag',
    favoriteColor: 'From favorite Color to Description',
    price: { amount: '20', currency: 'euro' },
    colorChoice: { black: 'black', brown: 'brown', red: 'red' },
    img: 'https://i.imgur.com/G3ZWEv4.jpg',
  },
  {
    id: '10',
    name: 'Another Wonderful Male Bag',
    favoriteColor: 'From favorite Color to Description',
    price: { amount: '50', currency: 'euro' },
    colorChoice: { black: 'black', brown: 'brown', red: 'red' },
    img: 'https://i.imgur.com/G3ZWEv4.jpg',
  },
];
